store/items/urls.py
from django.conf.urls import url

from . import views

urlpatterns = [
    # Examples:
    # url(r'^$', 'store.views.home', name='home'),
    # url(r'^blog/', include('blog.urls')),

    url(r'^/$', views.index, name='index'),
    url(r'(?P<item_id>[0-9]+)/$', views.show, name='show'),
    url(r'^/cart/', views.cart, name='cart'),
    url(r'(?P<item_id>[0-9]+)/add$', views.add, name='add'),
    url(r'(?P<item_id>[0-9]+)/delete$', views.delete, name='delete'),
    url(r'/payment/$', views.payment, name='payment'),
    url(r'/thankyou$', views.thankyou, name='thankyou'),
    ]

store/store/urls.py
from django.conf.urls import include, url
from django.contrib import admin

urlpatterns = [
    url(r'^users', include('users.urls', namespace="users")),
    url(r'^items', include('items.urls', namespace="items")),
    url(r'^admin/', include(admin.site.urls)),
]

store/users/urls.py
from django.conf.urls import url

from . import views

urlpatterns = [
    # Examples:
    # url(r'^$', 'store.views.home', name='home'),
    # url(r'^blog/', include('blog.urls')),

    url(r'^/signup/$', views.signup, name='signup'),
    url(r'^/register/$', views.register, name='register'),
    url(r'^/log_in/$', views.log_in, name='log_in'),
    url(r'^/login_user/$', views.login_user, name='login_user'),
    url(r'^/profile/$', views.profile, name='profile'),
    url(r'^/logout/$', views.logoutnow, name='logoutnow'),


    

]

store/items/models.py
from django.db import models
from django.contrib.auth.models import User

# Create your models here.

class Item(models.Model):
	name = models.CharField(max_length=200)
	description = models.CharField(max_length=400)
	price = models.IntegerField()

	def __str__(self):
		# returns blog title as print str
		return self.name

class Order(models.Model):
	user = models.ForeignKey(User)
	items = models.ManyToManyField(Item)
	status = models.IntegerField()
	

store/users/models.py
from django.db import models

# Create your models here.

store/items/views.py
from django.shortcuts import render
from .models import Item, Order
from django.core.paginator import Paginator, EmptyPage, PageNotAnInteger
from django.http import HttpResponseRedirect, HttpResponse
from django.core import serializers
from django.contrib.auth import authenticate, login
from django.core.urlresolvers import reverse


# Create your views here.

def index(request):
	page = request.GET.get('page')
	search = request.GET.get('search')
	price = request.GET.get('price')

	our_items = Item.objects.all()	

	if search:
		our_items = Item.objects.filter(name__icontains=search)	

	if price:
		our_items = our_items.filter(price__lte=price)
	
	paginator = Paginator(our_items, 10)

	try:
		items = paginator.page(page)
	except PageNotAnInteger:
		items = paginator.page(1)
	except EmptyPage:
		items = paginator.page(paginator.num_pages)
	if request.GET.get('json'):
		data = serializers.serialize("json", our_items)
		return HttpResponse(data, content_type='application/json')
	else:	
		return render(request, 'items/index.html', {"items_list": items, "search_price" : price})

def show(request, item_id):
	#get_object_or_404(Disease, pk=disease_id)
	try:
	    item = Item.objects.get(pk=item_id)
	except Item.DoesNotExist:
	    raise Http404("Item does not exist")
	return render(request, 'items/show.html', {'item': item})

def cart(request):
	#check if they're logged in
	user = request.user
	if not user.is_authenticated():
		return render(request, 'users/login.html')

	all_orders = Order.objects.all()
	
	#check if they have orders staus of 1
	order = all_orders.filter(user=user.id).filter(status=1)
	if not order:
		return render(request, 'items/cart.html', {"items": [], "total" : 0})
		# print order
	items = order[0].items.all()
	total = 0

	for item in items:
		total += item.price

	return render(request, 'items/cart.html', {"items": items, "total" : total})

def add(request, item_id):
	user = request.user
	#check if they're logged in
	if not user.is_authenticated():
		return render(request, 'user/login.html')

		# refactor into method
	all_orders = Order.objects.all()
	
	#check if they have orders staus of 1
	order = all_orders.filter(user=user.id).filter(status=1)
	item = Item.objects.get(pk=item_id)
	
	if order:
		order[0].items.add(item)
	else:
		o = Order(user=user, status=1)
		o.save()
		o.items.add(item)
	
		
	return HttpResponseRedirect(reverse("items:cart"))

def delete(request, item_id):
	user = request.user
	if not user.is_authenticated():
		return render(request, 'user/login.html')

	all_orders = Order.objects.all()
	
	#check if they have orders staus of 1
	order = all_orders.filter(user=user.id).filter(status=1)
	item = Item.objects.get(pk=item_id)
	
	order[0].items.remove(item)

	return HttpResponseRedirect(reverse("items:cart"))

def payment(request):
	return render(request, 'items/payment.html')

def thankyou(request):
	user = request.user
	#check if they have orders staus of 1
	order = Order.objects.all().filter(user=user.id).filter(status=1)[0]
	order.status = 2
	order.save()
	return render(request, 'items/thankyou.html')

store/users/views.py
from django.shortcuts import render
from django.contrib.auth.models import User
from django.contrib.auth import authenticate, login
from django.template import RequestContext, loader
from django.contrib.auth import logout
from django.http import HttpResponseRedirect, HttpResponse
from django.core.urlresolvers import reverse


def signup(request):
	return render(request, 'users/signup.html')

def register(request):
	user = User.objects.create_user(request.POST['username'],request.POST['email'],request.POST['password'])
	username = request.POST['username']
	password = request.POST['password']
	user = authenticate(username=username, password=password)
	if user is not None:
		if user.is_active:
			login(request, user)
			return HttpResponseRedirect(reverse("users:profile"))
		else:
		# Return a 'disabled account' error message
			return HttpResponse("Disabled Account.")
	else:
		# Return an 'invalid login' error message.
		return HttpResponse("ERROR: Invalid Login")

def log_in(request):
	return render(request, 'users/log_in.html')

def login_user(request):
	username = request.POST['username']
	password = request.POST['password']
	user = authenticate(username=username, password=password)
	if user is not None:
		if user.is_active:
			login(request, user)
			# http redirect
			return HttpResponseRedirect(reverse("users:profile"))
		else:
		# Return a 'disabled account' error message
			return HttpResponse("Disabled Account.")
	else:
		# Return an 'invalid login' error message.
		return HttpResponse("ERROR: Invalid Login")

def profile(request):
	if request.user.is_authenticated():
		user = request.user
		return render(request, 'users/profile.html', {'user':user})
		#return HttpResponse("You're logged in!")
	else:
		return render(request, 'users/login.html')

def logoutnow(request):
	logout(request)
	return HttpResponseRedirect(reverse("items:index"))

store/items/templates/items/cart.html
{% include "header.html" %}

<h2>This, my friend, is your cart:</h2>
<!-- <div class="item-list">
    <h2>{{ item }} | ${{ item.price }}</h2>
    <p>{{ item.description }}</p>
    <a class="cart-link" href="#"><p class="add-to-cart">Add to Cart</p></a>
</div> -->

{% if items %}
    {% for item in items %}
    <div class="item-list">
        <a href="{% url 'items:show' item.id %}"><h3>{{ item }}</a>  |  ${{ item.price }}</h3>
        <p>{{ item.description }}</p>
        <a class="cart-link" href="/items/{{ item.id }}/delete"><p class="remove-to-cart">Remove from Cart</p></a>
    </div>
    {% endfor %}
    <div class="item-list">
    	<h3>Total: ${{ total }}</h3>
    	<a class="cart-link" href="/items/payment"><p class="remove-to-cart">Buy It All</p></a>
    </div>
{% else %}
    <p>No items are available.</p>
{% endif %}

store/items/templates/items/index.html
{% include "header.html" %}

<h2>Items. Lots of items.</h2>

<div>
<form style="margin: 0px; padding: 0px;" action="/items/" method="get">
    $0
    <input type="range" name="price" min="0" max="2000" step="10" value="{{ search_price }}" onchange="updateTextInput(this.value);">
    $2000
    $<input type="text" id="textInput" value="{{ search_price }}">
    <input type="submit" value="Filter By Price" />
</form>
</div>

{% if items_list %}
    {% for item in items_list %}
    <div class="item-list">
        <a href="{% url 'items:show' item.id %}"><h3>{{ item }}</a>  |  ${{ item.price }}</h3>
        <p>{{ item.description }}</p>
        <a class="cart-link" href="/items/{{ item.id }}/add"><p class="add-to-cart">Add to Cart</p></a>
    </div>
    {% endfor %}
{% else %}
    <p>No items are available.</p>
{% endif %}

<div class="pagination">
    <span class="step-links">
        {% if items_list.has_previous %}
            <a href="?page={{ contacts.previous_page_number }}">Previous</a>
        {% endif %}

        <span class="current">
            Page {{ items_list.number }} of {{ items_list.paginator.num_pages }}.
        </span>

        {% if items_list.has_next %}
            <a href="?page={{ items_list.next_page_number }}">Next</a>
        {% endif %}
    </span>
</div>

store/items/templates/items/payment.html
{% include "header.html" %}

<h2>Please complete payment:</h2>

<form style="margin: 0px; padding: 0px;" action="/items/thankyou" method="get">
    <input type="text" name="first_name" placeholder="First Name"/>
    <input type="text" name="last_name" placeholder="Last Name"/>
    <br><br>
    <input type="text" name="address" placeholder="Street Address"/>
    <br>
    <input type="text" name="city" placeholder="City"/>
    <br>
    <input type="text" name="state" placeholder="State"/>
    <br>
    <input type="text" name="zip" placeholder="Zip"/>
    <br>
    <br>
    <input type="text" name="name_on_card" placeholder="Name on Card"/>
    <input type="text" name="cc_number" placeholder="Credit Card Number"/><br>
    <input type="text" name="exp_month" placeholder="Exp Month"/>
    <input type="text" name="exp_year" placeholder="Exp Year"/>


    <br><br>
    <input type="submit" value="Pay" />
</form>

store/items/templates/items/show.html
{% include "header.html" %}

<div class="item-list">
    <h2>{{ item }} | ${{ item.price }}</h2>
    <p>{{ item.description }}</p>
    <a class="cart-link" href="/items/{{ item.id }}/add"><p class="add-to-cart">Add to Cart</p></a>
</div>

store/items/templates/items/thankyou.html
{% include "header.html" %}

<h2>
Thank you for your order.<br><br>
Our robot army is prepping it for shipment.
</h2>

store/templates/header.html
{% load staticfiles %}

<link rel="stylesheet" type="text/css" href="{% static 'users/style.css' %}" />

 <script type="text/javascript">
    function updateTextInput(val) {
      document.getElementById('textInput').value=val; 
    }
  </script>

<div class="title">
	<h1><a href="/items">Dave's Store of Oddities and Intrigues</a></h1>
</div>

<div id="navigation">
	<ul style="list-style: none;">
		<li><a href="/items">Shop</a></li>
		{% if user.is_authenticated %}
    	<li><a href="/users/logout">Logout</a></li>
		{% else %}
		<li><a href="/users/signup">Signup</a></li>
    	<li><a href="/users/log_in">Login</a></li>
		{% endif %}
		<li style="padding: 10px"><div>
	<form style="margin: 0px; padding: 0px;" action="/items/" method="get">
	    <input type="search" name="search" placeholder="Search"/>
	    <input type="submit" value="Search" />
	</form>
</div></li>
	</ul>
</div>

<hr>

store/users/templates/users/log_in.html
{% include "header.html" %}

<h2>Login</h2>

<form action="/users/login_user/" method="post">
{% csrf_token %}
    Username:<br>
    <input type="text" name="username"/>
    <br /><br>
    Password:<br>
    <input type="password" name="password"/>
    <br />
    <br>
    
<input type="submit" value="Login" />
</form>

store/users/templates/users/profile.html
{% include "header.html" %}

<h2>Profile</h2>

<p>Username: {{ user }}</p>
<p>Email: {{ user.email }}</p>
<p>Last Login: {{ user.last_login }}</p>

<a href="/users/logout/">Logout</a>

store/users/templates/users/signup.html
{% include "header.html" %}

<h2>New User Signup</h2>

<form action="/users/register/" method="post">
{% csrf_token %}
    Username:<br>
    <input type="text" name="username"/>
    <br /><br>
    Email:<br>
    <input type="email" name="email"/>
    <br /><br>
    Password:<br>
    <input type="password" name="password"/>
    <br />
    <br>
    
<input type="submit" value="Register" />
</form>